services:
  postgres:
    image: postgres
    container_name: postgres
    environment:
      - POSTGRES_USER=ferret
      - POSTGRES_PASSWORD=ferret321
      - POSTGRES_DB=ferretdb
    volumes:
      - ./pgdata:/var/lib/postgresql/data

  ferretdb:
    image: ghcr.io/ferretdb/ferretdb
    restart: on-failure
    ports:
      - 27017:27017
    environment:
      - FERRETDB_POSTGRESQL_URL=postgres://postgres:5432/ferretdb

networks:
  default:
    name: ferretdb
